// Puzzle-Bildergalerie. Neues Motiv hinzufuegen: Bild (16:9 Querformat) in
// images/full/<kategorie-ordner>/ und images/thumb/<kategorie-ordner>/ ablegen
// und hier einen weiteren Eintrag ergaenzen.
const PUZZLE_GALLERY = [
  { id: "guinea_pig", title: "Meerschweinchen", category: "Tiere", full: "images/full/tiere/guinea_pig.jpg", thumb: "images/thumb/tiere/guinea_pig.jpg" },
  { id: "rabbit", title: "Hase", category: "Tiere", full: "images/full/tiere/rabbit.jpg", thumb: "images/thumb/tiere/rabbit.jpg" },
  { id: "kitten", title: "Katzenbaby", category: "Tiere", full: "images/full/tiere/kitten.jpg", thumb: "images/thumb/tiere/kitten.jpg" },
  { id: "fox", title: "Fuchs im Wald", category: "Tiere", full: "images/full/tiere/fox.jpg", thumb: "images/thumb/tiere/fox.jpg" },
  { id: "owl", title: "Eule", category: "Tiere", full: "images/full/tiere/owl.jpg", thumb: "images/thumb/tiere/owl.jpg" },
  { id: "horse", title: "Pferd auf der Weide", category: "Tiere", full: "images/full/tiere/horse.jpg", thumb: "images/thumb/tiere/horse.jpg" },
  { id: "panda", title: "Panda", category: "Tiere", full: "images/full/tiere/panda.jpg", thumb: "images/thumb/tiere/panda.jpg" },
  { id: "sunset", title: "Sonnenuntergang", category: "Landschaft", full: "images/full/landschaft/sunset.jpg", thumb: "images/thumb/landschaft/sunset.jpg" },
  { id: "beach", title: "Traumstrand", category: "Landschaft", full: "images/full/landschaft/beach.jpg", thumb: "images/thumb/landschaft/beach.jpg" },
  { id: "mountains", title: "Bergpanorama", category: "Landschaft", full: "images/full/landschaft/mountains.jpg", thumb: "images/thumb/landschaft/mountains.jpg" },
  { id: "autumn_forest", title: "Herbstwald", category: "Landschaft", full: "images/full/landschaft/autumn_forest.jpg", thumb: "images/thumb/landschaft/autumn_forest.jpg" },
  { id: "waterfall", title: "Wasserfall", category: "Landschaft", full: "images/full/landschaft/waterfall.jpg", thumb: "images/thumb/landschaft/waterfall.jpg" },
  { id: "desert", title: "Wuestenduenen", category: "Landschaft", full: "images/full/landschaft/desert.jpg", thumb: "images/thumb/landschaft/desert.jpg" },
  { id: "aurora", title: "Polarlicht", category: "Landschaft", full: "images/full/landschaft/aurora.jpg", thumb: "images/thumb/landschaft/aurora.jpg" },
  { id: "flower_tulips", title: "Tulpenfeld", category: "Blumen", full: "images/full/blumen/flower_tulips.jpg", thumb: "images/thumb/blumen/flower_tulips.jpg" },
  { id: "flower_sunflowers", title: "Sonnenblumenfeld", category: "Blumen", full: "images/full/blumen/flower_sunflowers.jpg", thumb: "images/thumb/blumen/flower_sunflowers.jpg" },
  { id: "flower_roses", title: "Rosengarten", category: "Blumen", full: "images/full/blumen/flower_roses.jpg", thumb: "images/thumb/blumen/flower_roses.jpg" },
  { id: "flower_meadow", title: "Wildblumenwiese", category: "Blumen", full: "images/full/blumen/flower_meadow.jpg", thumb: "images/thumb/blumen/flower_meadow.jpg" },
  { id: "flower_lavender", title: "Lavendelfeld", category: "Blumen", full: "images/full/blumen/flower_lavender.jpg", thumb: "images/thumb/blumen/flower_lavender.jpg" },
  { id: "flower_cherry_blossom", title: "Kirschbluete", category: "Blumen", full: "images/full/blumen/flower_cherry_blossom.jpg", thumb: "images/thumb/blumen/flower_cherry_blossom.jpg" },
  { id: "city_skyline_night", title: "Skyline bei Nacht", category: "Staedte bei Nacht", full: "images/full/staedte-bei-nacht/city_skyline_night.jpg", thumb: "images/thumb/staedte-bei-nacht/city_skyline_night.jpg" },
  { id: "city_street_neon", title: "Neonstrasse", category: "Staedte bei Nacht", full: "images/full/staedte-bei-nacht/city_street_neon.jpg", thumb: "images/thumb/staedte-bei-nacht/city_street_neon.jpg" },
  { id: "city_bridge_night", title: "Bruecke bei Nacht", category: "Staedte bei Nacht", full: "images/full/staedte-bei-nacht/city_bridge_night.jpg", thumb: "images/thumb/staedte-bei-nacht/city_bridge_night.jpg" },
  { id: "city_rainy_street", title: "Regennasse Strasse bei Nacht", category: "Staedte bei Nacht", full: "images/full/staedte-bei-nacht/city_rainy_street.jpg", thumb: "images/thumb/staedte-bei-nacht/city_rainy_street.jpg" },
  { id: "city_harbor_night", title: "Hafenstadt bei Nacht", category: "Staedte bei Nacht", full: "images/full/staedte-bei-nacht/city_harbor_night.jpg", thumb: "images/thumb/staedte-bei-nacht/city_harbor_night.jpg" },
  { id: "city_rooftop_view", title: "Dachterrasse mit Stadtblick", category: "Staedte bei Nacht", full: "images/full/staedte-bei-nacht/city_rooftop_view.jpg", thumb: "images/thumb/staedte-bei-nacht/city_rooftop_view.jpg" },
  { id: "space_nebula", title: "Sternennebel", category: "Weltraum", full: "images/full/weltraum/space_nebula.jpg", thumb: "images/thumb/weltraum/space_nebula.jpg" },
  { id: "space_planets", title: "Planeten und Monde", category: "Weltraum", full: "images/full/weltraum/space_planets.jpg", thumb: "images/thumb/weltraum/space_planets.jpg" },
  { id: "space_moon", title: "Erdaufgang ueber dem Mond", category: "Weltraum", full: "images/full/weltraum/space_moon.jpg", thumb: "images/thumb/weltraum/space_moon.jpg" },
  { id: "space_station", title: "Raumstation im Orbit", category: "Weltraum", full: "images/full/weltraum/space_station.jpg", thumb: "images/thumb/weltraum/space_station.jpg" },
  { id: "space_supernova", title: "Supernova-Explosion", category: "Weltraum", full: "images/full/weltraum/space_supernova.jpg", thumb: "images/thumb/weltraum/space_supernova.jpg" },
  { id: "space_asteroid_field", title: "Asteroidenfeld", category: "Weltraum", full: "images/full/weltraum/space_asteroid_field.jpg", thumb: "images/thumb/weltraum/space_asteroid_field.jpg" },
  { id: "underwater_reef", title: "Korallenriff", category: "Unterwasserwelt", full: "images/full/unterwasserwelt/underwater_reef.jpg", thumb: "images/thumb/unterwasserwelt/underwater_reef.jpg" },
  { id: "underwater_whale", title: "Buckelwal", category: "Unterwasserwelt", full: "images/full/unterwasserwelt/underwater_whale.jpg", thumb: "images/thumb/unterwasserwelt/underwater_whale.jpg" },
  { id: "underwater_turtle", title: "Meeresschildkroete", category: "Unterwasserwelt", full: "images/full/unterwasserwelt/underwater_turtle.jpg", thumb: "images/thumb/unterwasserwelt/underwater_turtle.jpg" },
  { id: "underwater_dolphins", title: "Delfine im Sonnenlicht", category: "Unterwasserwelt", full: "images/full/unterwasserwelt/underwater_dolphins.jpg", thumb: "images/thumb/unterwasserwelt/underwater_dolphins.jpg" },
  { id: "underwater_shipwreck", title: "Schiffswrack am Meeresgrund", category: "Unterwasserwelt", full: "images/full/unterwasserwelt/underwater_shipwreck.jpg", thumb: "images/thumb/unterwasserwelt/underwater_shipwreck.jpg" },
  { id: "underwater_octopus", title: "Oktopus im Korallengarten", category: "Unterwasserwelt", full: "images/full/unterwasserwelt/underwater_octopus.jpg", thumb: "images/thumb/unterwasserwelt/underwater_octopus.jpg" },
  { id: "winter_forest", title: "Winterwald", category: "Winter", full: "images/full/winter/winter_forest.jpg", thumb: "images/thumb/winter/winter_forest.jpg" },
  { id: "winter_village", title: "Alpendorf im Schnee", category: "Winter", full: "images/full/winter/winter_village.jpg", thumb: "images/thumb/winter/winter_village.jpg" },
  { id: "winter_frozen_lake", title: "Zugefrorener Bergsee", category: "Winter", full: "images/full/winter/winter_frozen_lake.jpg", thumb: "images/thumb/winter/winter_frozen_lake.jpg" },
  { id: "winter_ski_slope", title: "Skipiste im Morgenlicht", category: "Winter", full: "images/full/winter/winter_ski_slope.jpg", thumb: "images/thumb/winter/winter_ski_slope.jpg" },
  { id: "winter_igloo_aurora", title: "Iglu unter dem Polarlicht", category: "Winter", full: "images/full/winter/winter_igloo_aurora.jpg", thumb: "images/thumb/winter/winter_igloo_aurora.jpg" },
  { id: "winter_frozen_waterfall", title: "Gefrorener Wasserfall", category: "Winter", full: "images/full/winter/winter_frozen_waterfall.jpg", thumb: "images/thumb/winter/winter_frozen_waterfall.jpg" },
  { id: "comic_treehouse_village", title: "Baumhausdorf im Zauberwald", category: "Comic", full: "images/full/comic/comic_treehouse_village.jpg", thumb: "images/thumb/comic/comic_treehouse_village.jpg" },
  { id: "comic_robot_market", title: "Roboter-Basar der Zukunft", category: "Comic", full: "images/full/comic/comic_robot_market.jpg", thumb: "images/thumb/comic/comic_robot_market.jpg" },
  { id: "comic_pirate_ship", title: "Piratenschiff im Sturm", category: "Comic", full: "images/full/comic/comic_pirate_ship.jpg", thumb: "images/thumb/comic/comic_pirate_ship.jpg" },
  { id: "comic_dragon_castle", title: "Drache ueber der Burg", category: "Comic", full: "images/full/comic/comic_dragon_castle.jpg", thumb: "images/thumb/comic/comic_dragon_castle.jpg" },
  { id: "comic_alien_planet", title: "Fantasie-Alienplanet", category: "Comic", full: "images/full/comic/comic_alien_planet.jpg", thumb: "images/thumb/comic/comic_alien_planet.jpg" },
  { id: "comic_candy_kingdom", title: "Suessigkeiten-Koenigreich", category: "Comic", full: "images/full/comic/comic_candy_kingdom.jpg", thumb: "images/thumb/comic/comic_candy_kingdom.jpg" },
];

const PIECE_COUNT_OPTIONS = [50, 100, 250, 500, 600];

// Kategorien mit Anzeige-Reihenfolge und Symbol fuer die Ordner-Kacheln im
// Startbildschirm. Neue Kategorie hinzufuegen: hier ergaenzen, dann Motive
// mit passendem "category"-Wert in PUZZLE_GALLERY eintragen.
const PUZZLE_CATEGORIES = [
  { key: "Tiere", emoji: "🐾" },
  { key: "Landschaft", emoji: "🏞️" },
  { key: "Blumen", emoji: "🌸" },
  { key: "Staedte bei Nacht", emoji: "🌃" },
  { key: "Weltraum", emoji: "🌌" },
  { key: "Unterwasserwelt", emoji: "🐠" },
  { key: "Winter", emoji: "❄️" },
  { key: "Comic", emoji: "💥" },
];
