// Puzzle-Bildergalerie. Neues Motiv hinzufuegen: Bild (16:9 Querformat) in images/full/
// und images/thumb/ ablegen und hier einen weiteren Eintrag ergaenzen.
const PUZZLE_GALLERY = [
  { id: "guinea_pig", title: "Meerschweinchen", category: "Tiere", full: "images/full/guinea_pig.jpg", thumb: "images/thumb/guinea_pig.jpg" },
  { id: "rabbit", title: "Hase", category: "Tiere", full: "images/full/rabbit.jpg", thumb: "images/thumb/rabbit.jpg" },
  { id: "kitten", title: "Katzenbaby", category: "Tiere", full: "images/full/kitten.jpg", thumb: "images/thumb/kitten.jpg" },
  { id: "sunset", title: "Sonnenuntergang", category: "Landschaft", full: "images/full/sunset.jpg", thumb: "images/thumb/sunset.jpg" },
  { id: "beach", title: "Traumstrand", category: "Landschaft", full: "images/full/beach.jpg", thumb: "images/thumb/beach.jpg" },
  { id: "mountains", title: "Bergpanorama", category: "Landschaft", full: "images/full/mountains.jpg", thumb: "images/thumb/mountains.jpg" },
  { id: "flower_tulips", title: "Tulpenfeld", category: "Blumen", full: "images/full/flower_tulips.jpg", thumb: "images/thumb/flower_tulips.jpg" },
  { id: "flower_sunflowers", title: "Sonnenblumenfeld", category: "Blumen", full: "images/full/flower_sunflowers.jpg", thumb: "images/thumb/flower_sunflowers.jpg" },
  { id: "flower_roses", title: "Rosengarten", category: "Blumen", full: "images/full/flower_roses.jpg", thumb: "images/thumb/flower_roses.jpg" },
  { id: "flower_meadow", title: "Wildblumenwiese", category: "Blumen", full: "images/full/flower_meadow.jpg", thumb: "images/thumb/flower_meadow.jpg" },
  { id: "fox", title: "Fuchs im Wald", category: "Tiere", full: "images/full/fox.jpg", thumb: "images/thumb/fox.jpg" },
  { id: "owl", title: "Eule", category: "Tiere", full: "images/full/owl.jpg", thumb: "images/thumb/owl.jpg" },
  { id: "horse", title: "Pferd auf der Weide", category: "Tiere", full: "images/full/horse.jpg", thumb: "images/thumb/horse.jpg" },
  { id: "panda", title: "Panda", category: "Tiere", full: "images/full/panda.jpg", thumb: "images/thumb/panda.jpg" },
  { id: "autumn_forest", title: "Herbstwald", category: "Landschaft", full: "images/full/autumn_forest.jpg", thumb: "images/thumb/autumn_forest.jpg" },
  { id: "waterfall", title: "Wasserfall", category: "Landschaft", full: "images/full/waterfall.jpg", thumb: "images/thumb/waterfall.jpg" },
  { id: "desert", title: "Wuestenduenen", category: "Landschaft", full: "images/full/desert.jpg", thumb: "images/thumb/desert.jpg" },
  { id: "aurora", title: "Polarlicht", category: "Landschaft", full: "images/full/aurora.jpg", thumb: "images/thumb/aurora.jpg" },
  { id: "flower_lavender", title: "Lavendelfeld", category: "Blumen", full: "images/full/flower_lavender.jpg", thumb: "images/thumb/flower_lavender.jpg" },
  { id: "flower_cherry_blossom", title: "Kirschbluete", category: "Blumen", full: "images/full/flower_cherry_blossom.jpg", thumb: "images/thumb/flower_cherry_blossom.jpg" },
  { id: "city_skyline_night", title: "Skyline bei Nacht", category: "Staedte bei Nacht", full: "images/full/city_skyline_night.jpg", thumb: "images/thumb/city_skyline_night.jpg" },
  { id: "city_street_neon", title: "Neonstrasse", category: "Staedte bei Nacht", full: "images/full/city_street_neon.jpg", thumb: "images/thumb/city_street_neon.jpg" },
  { id: "city_bridge_night", title: "Bruecke bei Nacht", category: "Staedte bei Nacht", full: "images/full/city_bridge_night.jpg", thumb: "images/thumb/city_bridge_night.jpg" },
  { id: "space_nebula", title: "Sternennebel", category: "Weltraum", full: "images/full/space_nebula.jpg", thumb: "images/thumb/space_nebula.jpg" },
  { id: "space_planets", title: "Planeten und Monde", category: "Weltraum", full: "images/full/space_planets.jpg", thumb: "images/thumb/space_planets.jpg" },
  { id: "space_moon", title: "Erdaufgang ueber dem Mond", category: "Weltraum", full: "images/full/space_moon.jpg", thumb: "images/thumb/space_moon.jpg" },
  { id: "underwater_reef", title: "Korallenriff", category: "Unterwasserwelt", full: "images/full/underwater_reef.jpg", thumb: "images/thumb/underwater_reef.jpg" },
  { id: "underwater_whale", title: "Buckelwal", category: "Unterwasserwelt", full: "images/full/underwater_whale.jpg", thumb: "images/thumb/underwater_whale.jpg" },
  { id: "winter_forest", title: "Winterwald", category: "Winter", full: "images/full/winter_forest.jpg", thumb: "images/thumb/winter_forest.jpg" },
  { id: "winter_village", title: "Alpendorf im Schnee", category: "Winter", full: "images/full/winter_village.jpg", thumb: "images/thumb/winter_village.jpg" },
];

const PIECE_COUNT_OPTIONS = [50, 100, 250, 500, 600];
